name: stale issues and pull requests

on:
  push:
    branches: [ main, dev ]
  # pull_request:
  #   branches: [ main, dev]
    
#   schedule:
#   - cron: '24 14 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # issues
#         stale-issue-message: 'This issue is stale because it has been open 15 day with no activity. Remove stale label or comment or this will be closed in 5 days'
#         days-before-stale: 15
#         days-before-close: 5

        # pr
        stale-pr-message: 'This PR is stale because it has been open 15 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        close-pr-message: 'This PR was closed because it has been stalled for 5 days with no activity.'
        days-before-pr-stale: 15
        days-before-pr-close: 5

        # 30 days
        # stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
        # days-before-stale: 30
        # days-before-close: 5
        
